<a href="https://colab.research.google.com/github/felipeapgodoi/MetodosNumericos2020_3/blob/master/ProblemaDoLago_FelipeGodoi_EliminacaoGauss_Versao2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# Universidade Federal de Uberlândia
# Programa de Pós Graduação Em Engenharia Química
# Métodos Numéricos Aplicados à Engenharia Química
# Aluno: Felipe Augusto Paes de Godoi
# Atividade 01: Problema Do Lago
# Balanço de massa de PCB nos lagos:
# Lago Superior: 72 * Cs = 180
# Lago Michigan: 38 * Cm = 810
# Lago Huron: 72 * Cs + 38 * Cm - 160 * Ch = -630
# Lago Erie: 160 * Ch - 185 * Ce = -2750
# Lago Ontario: 185 * Ce - 215 * Co = -3820

import numpy as np
import time
import matplotlib.pyplot as plt
import numpy.linalg as npla

########################################################
# Function to decompose the matrix
# in an upper triangular form
########################################################

def LU(A,Entradas):
  # get the size of the system
  n = len(Entradas)
  
  # check the size
  
  if (A.shape[0] != n) or (A.shape[1] != n):
    print('\t Inconsistent size in LU decomposition')
    info = 0
    return M,info

  # create the augmented matrix
  M = np.zeros((n,n+1))
  M[:,:-1] = A
  M[:,-1] = Entradas

  # loop through all the colum
  # to get rid of the lower part
  for iC in range(n-1):
    # for each column loop over all the lines
    # that are below the diagonal
    # to set to 0 their elements
    for iL in range(iC+1,n):
      # check if the diagonal element
      # is null
      if(M[iC,iC] == 0):
        print('\t Zero on the diagonal, LU failed')
        info = 0
        return M,info
      # eliminate the element
      M[iL,:] = M[iL,:] - M[iL,iC]/M[iC,iC] * M[iC,:]

   # if we succed we return info = 1 and the upper augmetned matrix

  info = 1
  return M,info

In [7]:
########################################################
# Function to backsubstitute the results
# and get the final solution
########################################################
def BS(M):
  # get the size of the matrix
  n = M.shape[0]
  # loop over all the lines
  # starting by the end
  for iL in range(n-1,-1,-1):
    # check if we have diagonal elements on the diagonal
    if(M[iL,iL] == 0):
      print('\t Zero on the diagonal, LU failed')
      info = 0
      return M,info
    # divide the line by the diagonal element of M
    M[iL,:] /= M[iL,iL]
    
    # loop over all the lines that are above this onef
    for iLL in range(iL-1,-1,-1):
      M[iLL,:] -= M[iLL,iL]*M[iL,:]

  info = 1
  x=M[:,n]
  return x,info

########################################################
########################################################

In [8]:
# create the matrix A
A = np. array ([[72.0 ,0.0 ,0.0 ,0.0 ,0.0] ,[0.0 ,38.0 ,0.0 ,0.0 ,0.0] , [72.0 ,38.0 ,-160.0, 0.0 ,0.0] , [0.0 ,0.0 ,160.0 ,-185.0 ,0.0] , [0.0 ,0.0 ,0.0 ,185.0 ,-215.0]])

# create the right-hand side
Entradas = np. array ([180.0 ,810.0 ,-630.0 ,-2750.0 ,-3820.0])

M,info = LU(A,Entradas)
x,info = BS(M)

# print the solution
print(x)

# check the solution
check_sol = np.dot(A,x)
print(check_sol)


[ 2.5        21.31578947 10.125      23.62162162 38.09302326]
[  180.   810.  -630. -2750. -3820.]


In [9]:
# Balanço de massa de PCB nos lagos considerando uma corrente de bypass saindo do Lago Michigan para o Lago Ontario
# Lago Superior: 72 * Cs = 180
# Lago Michigan: 58 * Cm = 810
# Lago Huron: 72 * Cs + 38 * Cm - 160 * Ch = -630
# Lago Erie: 160 * Ch - 185 * Ce = -2750
# Lago Ontario: 20 * Cm + 185 * Ce - 215 * Co = -3820


In [10]:
# create the matrix A
A = np. array ([[72.0 ,0.0 ,0.0 ,0.0 ,0.0] ,[0.0 ,58.0 ,0.0 ,0.0 ,0.0] , [72.0 ,38.0 ,-160.0, 0.0 ,0.0] , [0.0 ,0.0 ,160.0 ,-185.0 ,0.0] , [0.0 ,20.0 ,0.0 ,185.0 ,-215.0]])

# create the right-hand side
Entradas = np. array ([180.0 ,810.0 ,-630.0 ,-2750.0 ,-3820.0])

M,info = LU(A,Entradas)
x,info = BS(M)

# print the solution
print(x)

# check the solution
check_sol = np.dot(A,x)
print(check_sol)


[ 2.5        13.96551724  8.37931034 22.11183597 38.09302326]
[  180.   810.  -630. -2750. -3820.]
