<a href="https://colab.research.google.com/github/felipeapgodoi/MetodosNumericos2020_3/blob/master/ProblemaDoLago_FelipeGodoi_EliminacaoGauss_Versao3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Universidade Federal de Uberlândia
# Programa de Pós Graduação Em Engenharia Química
# Métodos Numéricos Aplicados à Engenharia Química
# Aluno: Felipe Augusto Paes de Godoi
# Atividade 01: Problema Do Lago
# Balanço de massa de PCB nos lagos:
# Lago Superior: 72 * Cs = 180
# Lago Michigan: 38 * Cm = 810
# Lago Huron: 72 * Cs + 38 * Cm - 160 * Ch = -630
# Lago Erie: 160 * Ch - 185 * Ce = -2750
# Lago Ontario: 185 * Ce - 215 * Co = -3820


import numpy as np
import time
import matplotlib.pyplot as plt
import numpy.linalg as npla


In [9]:
!git clone https://github.com/felipeapgodoi/MetodosNumericos2020_3 #clonar do Github
%cd MetodosNumericos2020_3

Cloning into 'MetodosNumericos2020_3'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 45 (delta 23), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (45/45), done.
/content/MetodosNumericos2020_3/MetodosNumericos2020_3


In [10]:
'''
# caso fosse no computador
import os 
Local="C://Endereco da pasta"
os.chdir(Local) 
'''

'\n# caso fosse no computador\nimport os \nLocal="C://Endereco da pasta"\nos.chdir(Local) \n'

In [11]:
from EliminacaoGauss import LU, BS

In [12]:
# create the matrix A
A = np. array ([[72.0 ,0.0 ,0.0 ,0.0 ,0.0] ,[0.0 ,38.0 ,0.0 ,0.0 ,0.0] , [72.0 ,38.0 ,-160.0, 0.0 ,0.0] , [0.0 ,0.0 ,160.0 ,-185.0 ,0.0] , [0.0 ,0.0 ,0.0 ,185.0 ,-215.0]])

# create the right-hand side
Entradas = np. array ([180.0 ,810.0 ,-630.0 ,-2750.0 ,-3820.0])

M,info = LU(A,Entradas)
x,info = BS(M)

# print the solution
print(x)

# check the solution
check_sol = np.dot(A,x)
print(check_sol)


[ 2.5        21.31578947 10.125      23.62162162 38.09302326]
[  180.   810.  -630. -2750. -3820.]


In [13]:
# Balanço de massa de PCB nos lagos considerando uma corrente de bypass saindo do Lago Michigan para o Lago Ontario
# Lago Superior: 72 * Cs = 180
# Lago Michigan: 58 * Cm = 810
# Lago Huron: 72 * Cs + 38 * Cm - 160 * Ch = -630
# Lago Erie: 160 * Ch - 185 * Ce = -2750
# Lago Ontario: 20 * Cm + 185 * Ce - 215 * Co = -3820


In [14]:
# create the matrix A
A = np. array ([[72.0 ,0.0 ,0.0 ,0.0 ,0.0] ,[0.0 ,58.0 ,0.0 ,0.0 ,0.0] , [72.0 ,38.0 ,-160.0, 0.0 ,0.0] , [0.0 ,0.0 ,160.0 ,-185.0 ,0.0] , [0.0 ,20.0 ,0.0 ,185.0 ,-215.0]])

# create the right-hand side
Entradas = np. array ([180.0 ,810.0 ,-630.0 ,-2750.0 ,-3820.0])

M,info = LU(A,Entradas)
x,info = BS(M)

# print the solution
print(x)

# check the solution
check_sol = np.dot(A,x)
print(check_sol)


[ 2.5        13.96551724  8.37931034 22.11183597 38.09302326]
[  180.   810.  -630. -2750. -3820.]
