<a href="https://colab.research.google.com/github/felipeapgodoi/MetodosNumericos2020_3/blob/master/SegundaAula_Metodos_Numericos2020_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#testando o primeiro comando
print ('Hello world')
print ('hello world, i am envolving' )

Hello world
hello world, i am envolving


In [2]:
for k in range(2):
  for i in range(2):
    for j in range(2):
      print ('k=',k,'i=',i,'j=',j)

k= 0 i= 0 j= 0
k= 0 i= 0 j= 1
k= 0 i= 1 j= 0
k= 0 i= 1 j= 1
k= 1 i= 0 j= 0
k= 1 i= 0 j= 1
k= 1 i= 1 j= 0
k= 1 i= 1 j= 1


In [3]:
for k in range(2):
  for i in range(2):
    for j in range(2):
      print ('k=',k,'i=',i,'j=',j)
  print('==================')

k= 0 i= 0 j= 0
k= 0 i= 0 j= 1
k= 0 i= 1 j= 0
k= 0 i= 1 j= 1
k= 1 i= 0 j= 0
k= 1 i= 0 j= 1
k= 1 i= 1 j= 0
k= 1 i= 1 j= 1


In [4]:
x=[]#lista exemplo
w=[]
for i in range(3):
  for j in range(3):
    x.append(j)
  w.append(x)
  print(w)

[[0, 1, 2]]
[[0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2]]
[[0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]]


In [5]:
#lista exemplo
y=[]
for i in range(3):
  x=[]
  for j in range(3):
    x.append(j)
  y.append(x)
print(y)

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [6]:
print(y)

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]


In [7]:
import pandas as pd
import numpy as np


In [8]:
df=pd.DataFrame(y)
print(df)

   0  1  2
0  0  1  2
1  0  1  2
2  0  1  2


In [9]:
mat=np.array(y)
print(mat)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [10]:
mat[0,1]=99
print(mat)

[[ 0 99  2]
 [ 0  1  2]
 [ 0  1  2]]


In [11]:
print(mat[0,:])

[ 0 99  2]


In [12]:
print(mat[:,0])

[0 0 0]


In [13]:
# recaptulando
#tem o formato lista
#tem o formato dataframe
#tem o formato numpy array
#indice começa no zero
#tem varias situaçoes em que e possivel converter formato

In [15]:
n=5
#lista exemplo
y=[]
for i in range(n):
  x=[]
  for j in range(n):
    x.append(j)
  y.append(x)
print(y)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [16]:
def Lista(nn):
  y=[]
  for i in range(nn):
    x=[]
    for j in range(nn):
      x.append(j)
    y.append(x)
  return y
  

In [19]:
w=Lista(6)
print(w)


[[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]]
